# Database Configuration
# The PGDATABASE_URL env var will be parsed at runtime
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=postgres

# Druid Pool
db.initialSize=5
db.minIdle=5
db.maxActive=20
db.maxWait=60000
db.timeBetweenEvictionRunsMillis=60000
db.minEvictableIdleTimeMillis=300000
db.validationQuery=SELECT 1

# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.hbm2ddl.auto=none
hibernate.current_session_context_class=thread
